server:
  port: 8082

ribbon:
  euerka:
    enabled: true


#fastpass-service-local:
#    ribbon:
#      MaxAutoRetriesNextServer: 1
#      listOfServers: http://localhost:50316, http://localhost:50377
#      MaxAutoRetries: 0
#      OkToRetryOnAllOperations: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

fastpass-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

spring:
  rabbitmq:
    host: docker.me
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
#       output:
        fastpassTollChannel:
          destination: fastpasstoll
          producer:
            partitionKeyExpression: payload.stationId
            partitionCount: 3
